controller_type: JOINT_IMPEDANCE

is_delta: false

traj_interpolator_cfg:
  traj_interpolator_type: LINEAR_JOINT_POSITION
  time_fraction: 0.3

joint_kp: [5., 5., 5., 5., 0., 0., 0.]
joint_kd: null

state_estimator_cfg:
  is_estimation: false
  state_estimator_type: EXPONENTIAL_SMOOTHING
  alpha_q: 0.9
  alpha_dq: 0.9
  alpha_eef: 1.0
  alpha_eef_vel: 1.0
  
